project_id = "hizzel"

[db]
major_version = 17

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
